---
- name: Playbook to configure ansible controller post installation
  hosts: localhost
  connection: local
  vars:
    controller_validate_certs: false
  collections:
    - awx.awx

  tasks:
    - name: Build the same schedule using the rrule plugin
      schedule:
        name: 1-Update project-START-STOP-SOA-OPA 
        state: present
        unified_job_template: "41"
        rrule: "{{ query('awx.awx.schedule_rrule', 'week', start_date='2024-06-05 06:30:00', byweekday='MO,TU,WE,TH,FR') }}"
        validate_certs: false
      register: result